# example for docker-compose.yml
version: '3'
services:
  vocbench3:
    build: . 
    container_name: vb3
    volumes:
      - vb3:/data
    environment:
      - COLUMNS=236
      - LINES=66
      - TERM=xterm
    ports:
      - 1979:1979
volumes:
  vb3:


